backend:
  name: git-gateway
  branch: lambda-test # Branch to update (optional; defaults to master)
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
media_library: 
  name: uploadcare
  config:
    publicKey: 9bf6f709f65ed66722b0
  crop: 300x200 minimum
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog Posts" # Used in the UI
    folder: "content/blog/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    format: 'json'
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "tours"
    label: "Tours"
    folder: "content/tours"
    create: true
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    format: 'json'
    editor:
      preview: false
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Time Short", name: "timeShort", widget: "string", required: false}
      - {label: "Time Long", name: "timeLong", widget: "markdown", required: false}
      - {label: "Price Short", name: "priceShort", widget: "string", required: false}
      - {label: "Price Special", name: "priceSpecial", widget: "string", required: false}
      - {label: "Price Long", name: "priceLong", widget: "markdown", required: false}
      - {label: "Thumbnail", name: "thumbnail", widget: "image", required: false}
      - {label: "Gallery", name: "gallery", widget: "list", field: {label: Image, name: image, widget: image}}
      - {label: "Body", name: "body", widget: "markdown", required: true}
      - {label: "Sort", name: "sort", widget: "number", required: true}
      - {label: "Allow Online Booking", name: "allowBooking", widget: "boolean", required: false}
      - {label: "BookingID", name: "tourId", widget: "number", required: false}
      - label: 'Booking Options'
        name: 'booking'
        required: false
        widget: 'object'
        fields:
          - label: 'Tickets'
            name: 'tickets'
            widget: 'list'
            required: false
            fields:
              - {label: 'Name', name: 'label', widget: 'string', required: false}
              - {label: 'Description', name: 'description', widget: 'string', required: false}
              - {label: 'Price (in cents)', name: 'price', widget: 'number', required: false}
          - { label: 'Includes Pickup?', name: 'includesPickup', widget: 'boolean', default: false, required: false }
          - { label: 'Start Times', name: 'startTimes', widget: 'list', required: false, fields: [{label: 'time', name: 'time', widget: 'string'}]}
          - label: 'Confirmation Email Options'
            name: 'email'
            widget: 'object'
            required: false
            fields:
              - { label: 'Start Time', name: 'startTime', widget: 'string', required: false }
              - { label: 'Private Upgrade', name: 'private', hint: 'Will show after: "This is a PUBLIC tour."', widget: 'string', required: false }
              - { label: 'Tour Info', name: 'description', widget: 'string', required: false }
              - { label: 'Other Info', name: 'description2', widget: 'string', required: false }
              - { label: 'Gratuity', name: 'gratuity', widget: 'string', required: false }
              - { label: 'Include Boatlaunch Directions', name: 'boatlaunchDirections', widget: 'boolean', default: false, required: false }
              - { label: 'Include Circle Bar B Directions', name: 'stableDirections', widget: 'boolean', default: false, required: false }
  - name: "specials"
    label: "Specials"
    folder: "content/specials"
    create: true
    slug: "{{slug}}"
    format: 'json'
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Subheader", name: "subheader", widget: "string", required: false}
      - {label: "Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: true}
      - {label: "Sort", name: "sort", widget: "number", required: true}
  - name: "events"
    label: "Group Events"
    folder: "content/group-events"
    create: true
    slug: "{{slug}}"
    format: 'json'
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Group Sizes", name: "groupSizes", widget: "string", required: false}
      - {label: "Thumbnail", name: "thumbnail", widget: "image", required: false}
      - {label: "Gallery", name: "gallery", widget: "list", field: {label: Image, name: image, widget: image}}
      - {label: "Body", name: "body", widget: "markdown", required: true}
      - {label: "Sort", name: "sort", widget: "number", required: true}
  - name: "boat-charters"
    label: "Boat Charters"
    folder: "content/boat-charters"
    create: true
    slug: "{{slug}}"
    format: 'json'
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Price Short", name: "priceShort", widget: "string", required: false}
      - {label: "Price Long", name: "priceLong", widget: "markdown", required: false}
      - {label: "Group Sizes", name: "groupSizes", widget: "string", required: false}
      - {label: "Thumbnail", name: "thumbnail", widget: "image", required: false}
      - {label: "Gallery", name: "gallery", widget: "list", field: {label: Image, name: image, widget: image}}
      - {label: "Body", name: "body", widget: "markdown", required: true}
      - {label: "Sort", name: "sort", widget: "number", required: true}